- name: Thu thập trạng thái máy đào
  hosts: miners
  gather_facts: true
  become: yes

  tasks:

    - name: Load biến cấu hình đào
      include_vars: mining_vars.yml

    - name: Lấy hashrate (từ file log)
      shell: grep -oP '\d+\.\d+ H/s' /var/log/{{ mining_tool }}.log | tail -n1 || echo "0 H/s"
      register: hashrate_raw
      changed_when: false

    - name: Gửi dữ liệu về dashboard server
      uri:
        url: "http://{{ dashboard_server }}:5050/report"
        method: POST
        body_format: json
        body:
          worker: "{{ inventory_hostname }}"
          ip: "{{ ansible_host | default('localhost') }}"
          tool: "{{ mining_tool }}"
          coin: "{{ mining_tool | lower | regex_replace('xmrig', 'XMR') | regex_replace('srbminer', 'XMR') | regex_replace('deroluna', 'DERO') }}"
          wallet: "{{ wallet }}"
          pool: "{{ pool }}"
          threads: "{{ threads }}"
          hashrate: "{{ hashrate_raw.stdout }}"
          timestamp: "{{ ansible_date_time.iso8601 }}"
