- name: Triển khai công cụ đào CPU đơn giản
  hosts: miners
  become: yes

  vars_files:
    - mining_vars.yml

  tasks:

    - name: Cài các gói cần thiết (chỉ cho xmrig)
      apt:
        name:
          - git
          - curl
          - build-essential
          - cmake
          - libuv1-dev
          - libssl-dev
          - libhwloc-dev
        state: present
        update_cache: yes
      when: mining_tool == "xmrig"

    - name: Tải XMRig nếu cần
      git:
        repo: https://github.com/xmrig/xmrig.git
        dest: /opt/xmrig
        version: master
        force: no
        update: no
      when: mining_tool == "xmrig"

    - name: Build XMRig nếu chưa có
      shell: |
        mkdir -p /opt/xmrig/build
        cd /opt/xmrig/build
        cmake ..
        make -j$(nproc)
      args:
        creates: /opt/xmrig/build/xmrig
      when: mining_tool == "xmrig"

    - name: Cài xmrig vào /usr/local/bin
      copy:
        src: /opt/xmrig/build/xmrig
        dest: /usr/local/bin/xmrig
        mode: '0755'
        remote_src: yes
      when: mining_tool == "xmrig"

    - name: Giải nén và cài SRBMiner
      unarchive:
        src: "https://github.com/doktor83/SRBMiner-Multi/releases/download/2.9.2/SRBMiner-Multi-2-9-2-Linux.tar.gz"
        dest: /opt/srbminer
        remote_src: yes
        creates: /opt/srbminer/SRBMiner-MULTI
      when: mining_tool == "srbminer"

    - name: Tải deroluna
      unarchive:
        src: "https://github.com/DeroLuna/dero-miner/releases/download/v1.14/deroluna-v1.14_linux_hiveos_mmpos.tar.gz"
        dest: /opt/dero
        remote_src: yes
        creates: /opt/dero/dero-miner
      when: mining_tool == "dero"

    - name: Tạo config XMRig
      template:
        src: templates/xmrig_config_template.json
        dest: /opt/xmrig/config.json
      when: mining_tool == "xmrig"

    - name: Tạo config SRBMiner
      template:
        src: templates/srbminer_config_template.txt
        dest: /opt/srbminer/config.txt
      when: mining_tool == "srbminer"

    - name: Tạo config Dero
      template:
        src: templates/dero_config_template.txt
        dest: /opt/dero/config.txt
      when: mining_tool == "dero"

    - name: Tạo systemd service cho miner
      copy:
        dest: /etc/systemd/system/miner.service
        content: |
          [Unit]
          Description=Miner Service
          After=network.target

          [Service]
          ExecStart={{ 
            (mining_tool == 'xmrig') | ternary('/usr/local/bin/xmrig -c /opt/xmrig/config.json',
            (mining_tool == 'srbminer') | ternary('/opt/srbminer/SRBMiner-MULTI --config /opt/srbminer/config.txt',
            '/opt/dero/dero-miner --config /opt/dero/config.txt')) 
          }}
          Restart=always
          RestartSec=10

          [Install]
          WantedBy=multi-user.target

    - name: Bật và chạy miner service
      systemd:
        name: miner
        enabled: yes
        state: restarted
