- name: Triển khai công cụ đào CPU đơn giản
  hosts: miners
  become: yes
  vars_files:
    - mining_vars.yml

  tasks:
    - name: Cài các gói cần thiết (chỉ cho xmrig)
      apt:
        name:
          - git
          - curl
          - build-essential
          - cmake
          - libuv1-dev
          - libssl-dev
          - libhwloc-dev
        state: present
        update_cache: yes
      when: mining_tool == "xmrig"

    - name: Clone XMRig nếu chưa có
      git:
        repo: https://github.com/xmrig/xmrig.git
        dest: /opt/xmrig
        update: no
      when: mining_tool == "xmrig"

    - name: Build XMRig nếu chưa có
      shell: |
        mkdir -p /opt/xmrig/build
        cd /opt/xmrig/build
        cmake ..
        make -j"$(nproc)"
        cp xmrig /usr/local/bin/xmrig
      args:
        creates: /usr/local/bin/xmrig
      when: mining_tool == "xmrig"

    - name: Tải SRBMiner nếu chưa có
      unarchive:
        src: https://github.com/doktor83/SRBMiner-Multi/releases/download/2.9.2/SRBMiner-Multi-2-9-2-Linux.tar.gz
        dest: /opt/srbminer/
        remote_src: yes
        creates: /opt/srbminer/SRBMiner-MULTI
      when: mining_tool == "srbminer"

    - name: Tải DeroLuna nếu chưa có
      unarchive:
        src: https://github.com/DeroLuna/dero-miner/releases/download/v1.14/deroluna-v1.14_linux_hiveos_mmpos.tar.gz
        dest: /opt/dero/
        remote_src: yes
        creates: /opt/dero/dero-miner
      when: mining_tool == "dero"

    - name: Tạo file config tool
      template:
        src: "{{ mining_tool }}_config_template.{{ 'json' if mining_tool == 'xmrig' else 'txt' }}"
        dest: "/opt/{{ mining_tool }}/{{ 'config.json' if mining_tool == 'xmrig' else 'config.txt' }}"
        mode: '0644'

    - name: Tạo systemd service trực tiếp
      copy:
        dest: /etc/systemd/system/miner.service
        content: |
          [Unit]
          Description=Miner Service
          After=network.target

          [Service]
          ExecStart={{ 
            '/usr/local/bin/xmrig -c /opt/xmrig/config.json' if mining_tool == 'xmrig' else (
            '/opt/srbminer/SRBMiner-MULTI --config /opt/srbminer/config.txt' if mining_tool == 'srbminer' else
            '/opt/dero/dero-miner --config /opt/dero/config.txt') 
          }}
          Restart=always
          RestartSec=10

          [Install]
          WantedBy=multi-user.target
      notify: Reload systemd

    - name: Bật và khởi động miner.service
      systemd:
        name: miner
        enabled: yes
        state: restarted

  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: yes
