---
- name: Triển khai công cụ đào CPU (xmrig)
  hosts: miners
  become: yes

  vars:
    nas_ip: 192.168.10.6

  tasks:
    - name: Cài đặt các gói cần thiết để build xmrig
      apt:
        name:
          - git
          - curl
          - build-essential
          - cmake
          - libuv1-dev
          - libssl-dev
          - libhwloc-dev
        state: present
        update_cache: yes

    - name: Tạo thư mục chứa mã nguồn nếu chưa có
      file:
        path: /opt/xmrig
        state: directory
        mode: '0755'

    - name: Clone xmrig từ GitHub nếu chưa tồn tại
      git:
        repo: https://github.com/xmrig/xmrig.git
        dest: /opt/xmrig
        version: latest
        force: no
        update: no

    - name: Kiểm tra file xmrig đã được build chưa
      stat:
        path: /opt/xmrig/build/xmrig
      register: xmrig_binary

    - name: Tạo thư mục build nếu chưa có
      file:
        path: /opt/xmrig/build
        state: directory
        mode: '0755'

    - name: Chạy cmake trong /opt/xmrig/build
      command: cmake ..
      args:
        chdir: /opt/xmrig/build
      when: not xmrig_binary.stat.exists

    - name: Biên dịch xmrig bằng make -j
      command: make -j"{{ ansible_processor_cores | default(2) }}"
      args:
        chdir: /opt/xmrig/build
      when: not xmrig_binary.stat.exists

    - name: Sao chép xmrig vào /usr/local/bin
      copy:
        src: /opt/xmrig/build/xmrig
        dest: /usr/local/bin/xmrig
        mode: '0755'
        remote_src: yes
      when: xmrig_binary.stat.exists

    - name: Tải file config từ NAS Web (DSM Web Station)
      get_url:
        url: "http://{{ nas_ip }}/miner/xmrig_config.json"
        dest: /opt/xmrig/config.json
        mode: '0644'
        force: yes

    - name: Chạy xmrig nền (chỉ 1 lần)
      shell: "nohup /usr/local/bin/xmrig -c /opt/xmrig/config.json > /var/log/xmrig.log 2>&1 &"
      args:
        executable: /bin/bash
      async: 5
      poll: 0
      when: not xmrig_binary.stat.exists
